import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <section>{children}</section>
          <section>
            This is the main template layout for the app. Anything inside
            layout.js will be replicated across all routes. Typically you would
            add things like reusable components e.g. header, footer etc. or
            standardise the html attributes and metadata. The globals.css has
            been imported into layout.js so all routes will incorporate this
            stylesheet.
          </section>
        </main>
      </body>
    </html>
  );
}
